require:
  - rubocop-rails
  - rubocop-performance

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'redis-stable/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/FrozenStringLiteralComment:
  Enabled: false

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/ClassAndModuleChildren:
  Enabled: false

# Temporarily turn this off
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/RescueException:
  Enabled: true

Lint/Debugger:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: 'never'

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: 'around'
